version: "3.9"

networks:
  fpb-net:
    driver: bridge

volumes:
  postgresql_data: 
    driver: local

services:
  # Database
  postgresql:
    container_name: postgresql
    image: postgres:12.2-alpine
    env_file:
      - ".env"
    volumes:
      # - "./database/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql"
      - "./database/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh"
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fpb-net
  